global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using XamlViewer.DataContracts;
global using XamlViewer.DataContracts.Serialization;
global using XamlViewer.Models;
global using XamlViewer.Presentation;
global using XamlViewer.Services.Caching;
global using XamlViewer.Services.Endpoints;
global using Microsoft.UI.Xaml.Input;
global using CommunityToolkit.WinUI.Controls;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
